socialnetwork/socialnetwork/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import  DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField("What's on your mind?", validators=[DataRequired()])
    submit = SubmitField('Post')

socialnetwork/socialnetwork/core/views.py
from flask import render_template, request, Blueprint
from socialnetwork.models import Post

core = Blueprint('core', __name__)


@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page, per_page=10)
    return render_template('index.html', posts=posts)


@core.route('/info')
def info():
    return render_template('info.html')

socialnetwork/socialnetwork/posts/__init__.py
# posts init

socialnetwork/socialnetwork/posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from socialnetwork import db
from socialnetwork.models import Post
from socialnetwork.posts.forms import PostForm


posts = Blueprint('posts', __name__)


@posts.route('/create', methods=['GET','POST'])
@login_required
def create_post():
    form = PostForm()

    if form.validate_on_submit():

        post = Post(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(post)
        db.session.commit()
        flash("Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


@posts.route('/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, date=post.date, post=post)


@posts.route('/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('posts.post', blog_post_id=post.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data = post.title
        form.text.data = post.text
    return render_template('create_post.html', title='Update',
                           form=form)


@posts.route("/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

socialnetwork/socialnetwork/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required


from socialnetwork import db
from socialnetwork.models import User, Post
from socialnetwork.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from socialnetwork.users.picture_handler import  add_profile_pic


users = Blueprint('users', __name__)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)


@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)


@users.route('/<username>')
def user_posts(username):
    page = request.args.get('/page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date.desc()).pageinate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

socialnetwork/socialnetwork/templates/account.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <div align='center'>
      <h1>Welcome to the page for {{current_user.username}}</h1>
      <img align='center' src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
    </div>
  </div>

  <div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{form.hidden_tag()}}
      <div class="form-group">
        {{form.username.label(class='form-group')}}
        {{form.username(class='form-control')}}
      </div>

      <div class="form-group">
      {{form.email.label(class='form-group')}}
      {{form.email(class='form-control')}}
      </div>

      <div class="form-group">
      {{form.picture.label(class='form-group')}}
      {{form.picture(class='form-control')}}
      </div>

      <div class="form-group">
       {{form.submit(class='btn btn-primary')}}
      </div>


    </form>
  </div>

{% endblock %}

socialnetwork/socialnetwork/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
    <ul class="nav">
        <li class="nav-link"><a href="{{ url_for('core.index')}}">Home</a></li>
        <li class="nav-link"><a href="{{ url_for('core.info')}}">About</a></li>
        {% if current_user.is_authenticated %}
        <li class="nav-link"><a href="{{url_for('users.logout')}}">Log Out</a></li>
        <li class="nav-link"><a href="{{url_for('users.account')}}">Account</a></li>
        <li class="nav-link"><a href="{{url_for('posts.create_post')}}">Create Post</a></li>
        {% else %}
        <li class="nav-link"><a href="{{url_for('users.login')}}">Login</a></li>
        <li class="nav-link"><a href="{{url_for('users.register')}}">Register</a></li>
        {% endif %}
    </ul>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

socialnetwork/socialnetwork/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

socialnetwork/socialnetwork/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>The Social Network</h1>
    </div>

    <div class="container">

    {# Go through each post #}
    {% for post in posts.items %}

    <div class="card" >

      <div class="card-body">


        <h2><a class="card-title" href="  {{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('posts.post', post_id=post.id) }}" class="btn btn-primary">Read Post</a>
      </div>
    </div>

   {% endfor %}
    </div>

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
     </ul>
    </nav>
{% endblock %}

socialnetwork/socialnetwork/templates/info.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>Info about our company</h1>
        <p>lorem ipsum</p>
    </div>
{% endblock %}

socialnetwork/socialnetwork/templates/login.html
{% extends "base.html" %}

{% block content %}
    <form method="POST">
        {{form.hidden_tag()}}

        {{form.email.label}}{{form.email}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.submit()}}

    </form>
{% endblock %}

socialnetwork/socialnetwork/templates/post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('posts.update', post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

socialnetwork/socialnetwork/templates/register.html
{% extends "base.html" %}

{% block content %}
    <form method="POST">
        {{form.hidden_tag()}}

        {{form.email.label}}{{form.email}}<br>
        {{form.username.label}}{{form.username}}<br>
        {{form.password.label}}{{form.password}}<br>
        {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
        {{form.submit()}}

    </form>
{% endblock %}

socialnetwork/socialnetwork/templates/user_posts.html
{% extends "base.html %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div align="center">
                <h1>
                    Welcome to the page for {{user.username}}
                </h1>
                <img src="{{url_for('static', filename='profile_pics/'+user.profile_image)}}">
            </div>
        </div>
    </div>

{% for post in post.items %}
    <h2><a href="{{url_for('posts.post', post_id=post.id)}}">{{post.title}}</a></h2>
    Written By: <a href="{{url_for('users.user_post', username=post.author_username)}}">{{post.author.username}}</a>
    <p class="'text-muted">Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
    <br>
    <p>{{post.text}}</p>
    <br>
{% endfor %}

<nav aria-label='Page Navigation example'>
  <ul class="pagination justify-content-center">
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
      {% if posts.page == page_num %}
      <li class='page-item disabled'>
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% else %}
      <li class='page-item'>
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>

</nav>
{% endblock %}